#!/bin/sh

# Update challenge record
echo Create ${DDNS_DOMAIN} challenge record: ${CERTBOT_VALIDATION}
CMD="curl --silent https://www.duckdns.org/update?domains=${DDNS_DOMAIN}&token=${DUCKDNS_TOKEN}&txt=${CERTBOT_VALIDATION}"
RES=`${CMD}`
echo Command: ${CMD}
echo Response: ${RES}

# Wait for update to be propagated
sleep 60

# Check if succeeded
test "${RES}" = "OK"
