#!/bin/sh

# Update IP
echo Update ${DUCKDNS_DOMAIN} IP...
CMD="curl --silent https://www.duckdns.org/update?domains=${DUCKDNS_DOMAIN}&token=${DUCKDNS_TOKEN}&ip="
RES=`${CMD}`
echo Command: ${CMD}
echo Response: ${RES}

# Check if succeeded
test "${RES}" = "OK"
