version: '3'

services:
  sslduck:
    build:
      context: src
    container_name: sslduck
    volumes:
      - ./data:/etc/letsencrypt
      - ./log:/var/log/letsencrypt
    restart: unless-stopped
    environment:
      - UID=1234
      - GID=1234
      - DDNS_PROVIDER=duckdns
      - DDNS_DOMAIN=x.duckdns.org
      - DUCKDNS_TOKEN=x
      - LETSENCRYPT_DOMAIN=x.duckdns.org
    network_mode: bridge
