#!/usr/bin/python

import os
import ovh
import requests

# Create OVH client
client = ovh.Client(
  endpoint=os.getenv('OVH_API_SERVER'),
  application_key=os.getenv('OVH_APP_KEY'),
  application_secret=os.getenv('OVH_APP_SECRET'),
  consumer_key=os.getenv('OVH_CONSUMER_KEY'),
)

# Get A record(s)
print('Get', os.getenv('OVH_SUBDOMAIN')+'.'+os.getenv('OVH_ZONE'), 'A records')
response = client.get('/domain/zone/'+os.getenv('OVH_ZONE')+'/record',
  fieldType='A',
  subDomain=os.getenv('OVH_SUBDOMAIN')
)
print('Response:', response)

# Update A record(s)
for id in response:
  print('Update', os.getenv('OVH_SUBDOMAIN')+'.'+os.getenv('OVH_ZONE'), 'A record', id, 'IP:', os.getenv('IP'))
  response = client.put('/domain/zone/'+os.getenv('OVH_ZONE')+'/record/'+str(id),
    subDomain=os.getenv('OVH_SUBDOMAIN'),
    target=os.getenv('IP'),
    ttl=60
  )
  print('Response:', response)
client.post('/domain/zone/'+os.getenv('OVH_ZONE')+'/refresh')

# Check if succeeded
#test "${RES}" = "OK"
exit(0)
